### PR TITLE
Small PR to add a volume

### PR DESCRIPTION
**Pull request by mer-a-o**
## Description

Codebuild needs the docker image to have `VOLUME /var/lib/docker`. This line has already been added to clang and gnu Dockerfiles in the docker repo. 

### Issue(s) addressed

Not directly related to this issue but when I was working on it I discovered this missing line in intel Dockefile.
- fixes https://github.com/JCSDA-internal/jedi-stack/issues/137

### CODE REVIEW

**Review by climbfuji — COMMENTED** [review]
I can't see anythign wrong, but I can't test this myself right now. I assume you have done that and it all works as expected?

**Comment by mer-a-o** [comment]
Yes, I used this branch (with https://github.com/JCSDA-internal/jedi-stack/pull/152/files from jedi-stack) and built the Intel container. I tested the new container and it is now used in CodeBuild.

**Review by climbfuji — APPROVED** [review]
Approved since this has been tested and works.

**Comment by climbfuji** [comment]
@mer-a-o This PR is still open, is it still needed?

**Comment by mer-a-o** [comment]
Yes, we need to merge this.

**Pull request merged**
