### PR TITLE
Feature/update vagrantfile

### PR DESCRIPTION
**Pull request by mmiesch**
## Description

The creation of the jedi vagrant vm was failing because charliecloud updated their build procedure so that it now requires pip/pip3.    So, this upgrades python to python3 and also installs pip.

While I was at it, I also updated the OS to ubuntu 20.04 and updated singularity to version 3.8

### Issue(s) addressed

None

## Acceptance Criteria (Definition of Done)

the `vagrant up` command works as described in the JEDI documentation to create a new vagrant VM provisioned with Singularity and Charliecloud.

## Dependencies

None

## Impact

None

### CODE REVIEW

**Comment by mmiesch** [comment]
Oh - I also got rid of the centos version of the vagrantfile because it was out of date and unnecessary to maintain two.

**Review by rickgrubin — APPROVED** [review]
Nice to upgrade both Ubuntu and python versions

LGTM

**Comment by rickgrubin** [comment]
Out of curiosity, do you know the dot version of `python3`?

**Comment by mmiesch** [comment]
Not sure what you mean - what's the dot version?  This Vagrantfile, with the standard apt install on ubuntu 20.04 gives python version 3.8.10, if that's what you're asking.  There may be a more recent version from another apt repo if we need it.

**Comment by rickgrubin** [comment]
> Not sure what you mean - what's the dot version? This Vagrantfile, with the standard apt install on ubuntu 20.04 gives python version 3.8.10, if that's what you're asking. There may be a more recent version from another apt repo if we need it.

Thanks, that is what I mean by `dot version` -- `3.8.10`

I ask because `python3` is moving forward somewhat fast these days, and based on code that's being written within JCSDA (of which I'm aware), we want to see `version >= 3.7.5` at a minimum.

**Comment by mmiesch** [comment]
> > Not sure what you mean - what's the dot version? This Vagrantfile, with the standard apt install on ubuntu 20.04 gives python version 3.8.10, if that's what you're asking. There may be a more recent version from another apt repo if we need it.
> 
> Thanks, that is what I mean by `dot version` -- `3.8.10`
> 
> I ask because `python3` is moving forward somewhat fast these days, and based on code that's being written within JCSDA (of which I'm aware), we want to see `version >= 3.7.5` at a minimum.

Good to know - but remember, this is only the python version in the vagrant vm.  The usual workflow would be to then pull the singularity container, which would have it's own version of python.  It looks like the latest container is 3.8.5.  Strange that it's different since it was installed the same way, on ubuntu 20 with apt.  But, the container was last generated 8 weeks ago.  Did they go through 5 patches in 8 weeks?  That *is* fast!

**Comment by metdyn** [comment]
From user end, I report what I find.  Using the updated Vagrantfile, `vagrant up` finishes normally on Mac and `vagrant ssh` enters normally.  However, I didnot find a clear note on how to destroy the VM and the vagrant box. I think the information from  https://jointcenterforsatellitedataassimilation-jedi-docs.readthedocs-hosted.com/en/latest/using/jedi_environment/vagrant.html#
is insufficient to destroy the VM on Mac.  I find 
(s1.a) VirtualBox GUI  and remove the VM there.  
(s1.b) on Mac remove $HOME/VirtualBox VMs/jedibox   
(s2)  vagrant destroy and vagrant box remove. 
Of course, these may be well known to others. The html page can be updated. I am referring to 
```
However, it is possible that there might still be VirtualBox VMs on your machine that Vagrant has lost track of. You might notice this if you try to create a new VM with vagrant up and it complains that “A VirtualBox machine with the name jedibox already exists” (or a similar error message).

If this is the case, you can run VirtualBox directly to manage your VMs. This can be done through the command line with the vboxmanage command (run vboxmanage --help for information) but we recommend the VirtualBox GUI, which is more user-friendly.
```

**Comment by metdyn** [comment]
Here is my output from Mac:
    default:  GEN /home/vagrant/go/src/github.com/sylabs/singularity/scripts/go-generate
    default:  GO singularity
    default:     [+] GO_TAGS "containers_image_openpgp sylog oci_engine singularity_engine fakeroot_engine apparmor selinux seccomp"
    default:  GEN etc/bash_completion.d/singularity
    default:  GEN singularity.conf from /usr/local/etc/singularity/singularity.conf
    default:  CNI PLUGIN dhcp
    default: go: downloading github.com/d2g/dhcp4 v0.0.0-20170904100407-a1d1b6c41b1c
    default: go: downloading github.com/d2g/dhcp4client v1.0.0
    default:  CNI PLUGIN host-local
    default: go: downloading github.com/alexflint/go-filemutex v0.0.0-20171028004239-d358565f3c3f
...
    default:  INSTALL CNI CONFIGURATION FILES
    default:  INSTALL /usr/local/libexec/singularity/bin/starter
    default:  INSTALL /usr/local/var/singularity/mnt/session
    default:  INSTALL /usr/local/bin/run-singularity
    default:  INSTALL /usr/local/etc/singularity/capability.json
    default:  INSTALL /usr/local/etc/singularity/ecl.toml
    default:  INSTALL /usr/local/etc/singularity/seccomp-profiles/default.json
    default:  INSTALL /usr/local/etc/singularity/nvliblist.conf
    default:  INSTALL /usr/local/etc/singularity/rocmliblist.conf
    default:  INSTALL /usr/local/etc/singularity/cgroups/cgroups.toml
    default:  INSTALL /usr/local/etc/singularity/global-pgp-public
    default:  INSTALL SUID /usr/local/libexec/singularity/bin/starter-suid
    default:  DONE


Welcome to Ubuntu 20.04.2 LTS (GNU/Linux 5.4.0-77-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  System information as of Fri 23 Jul 2021 10:54:17 PM UTC

  System load:  2.73              Processes:             210
  Usage of /:   5.1% of 61.31GB   Users logged in:       0
  Memory usage: 2%                IPv4 address for eth0: 10.0.2.15
  Swap usage:   0%


This system is built by the Bento project by Chef Software
More information can be found at https://github.com/chef/bento

**Review by metdyn — APPROVED** [review]

**Review by srherbener — APPROVED** [review]
This works on my iMac (Big Sur, 11.5).

**Pull request merged**
